site_name: Requisitos de Software - Correios

repo_name: "2020.1-Correios"
repo_url: "https://github.com/Requisitos-de-Software/2020.1-Correios"

nav:
  - Home: index.md
  - Planejamento:
      - Roadmap: planejamento/roadmap.md
      - Ferramentas: planejamento/ferramentas.md
  - Pontos de Controle: pontosDeControle/pontosDeControle.md
  - Pré-Rastreabilidade:
      - Rich Picture: preRastreabilidade/richpicture.md
  - Elicitação:
      - Instrospecção: elicitacao/instrospeccao.md
      - Entrevista: elicitacao/entrevista.md
      - StoryTelling:
          - StoryTelling v1: elicitacao/storytelling.md
  - Priorização:
      - MoSCoW & First Things First: priorizacao/priorizacao.md
  - Modelagem:
      - Léxicos:
          - Léxico - v2: modelagem/lexicos/lexicos-v2.md
          - Léxico - v1: modelagem/lexicos/lexicos.md
      - Cenários:
          - Cenário - v2: modelagem/cenarios/cenarios-v2.md
          - Cenário - v1: modelagem/cenarios/cenarios.md  
      - Casos de Uso: modelagem/casosDeUso/casosDeUso.md
      - Especificação Suplementar: modelagem/especificacao/especificacaoSuplementar.md
      - Ágil:
        - Histórias de Usuário: modelagem/historiasDeUsuario/historiasDeUsuario.md
        - Product Backlog: modelagem/backlog/backlog.md
      - NFR Framework: modelagem/nfr/nfr-framework.md
  - Análise:
      - Validação:
        - Prototipagem: validacao/validacao.md
theme:
  name: material
  favicon: ./images/favicon.ico
  logo: ./images/logo-correios.png
  language: pt
  palette:
    primary: blue
