site_name: Requisitos de Software - Correios

repo_name: "2020.1-Correios"
repo_url: "https://github.com/Requisitos-de-Software/2020.1-Correios"

nav:
  - Home: index.md
  - Planejamento:
      - Roadmap: planejamento/roadmap.md
      - Ferramentas: planejamento/ferramentas.md
  - Elicitação:
      - Entrevista: elicitacao/entrevista.md
      - StoryTelling: 
        - StoryTelling v1: elicitacao/storytelling.md

theme:
  name: material
  favicon: ./images/favicon.ico
  logo: ./images/logo-correios.png
  language: pt
  palette:
    primary: blue
